/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author Nitin
 */

public class page22 extends HttpServlet {
public static String pricevalue;
public static String codevalue;
int c=0;
 public static String capcha;
 public static String banktype;
    @Override
    public void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        String title = "Page2";
        String docType = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 " + "Transitional//EN\">\n";
        out.println(" <!DOCTYPE HTML PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>"
+" <html xmlns='http://www.w3.org/1999/xhtml'><head><script src='Home%20shop_files/menu70.js'></script><link media='all' href='Home%20shop_files/widget53.css' type='text/css' rel='stylesheet'>"
  +" <meta name='title' content='Sony NEX 3 ( with E 18-55mm Lens) . Buy Best Sony NEX 3 ( with E 18-55mm Lens) at Lowest Price Online'>"
+" <meta name='description' content='Buy low price Sony NEX 3 ( with E 18-55mm Lens) . buy best Sony NEX 3 ( with E 18-55mm Lens) online at lowest price, SRMShop.com offers best deals to buy Sony NEX 3 ( with E 18-55mm Lens) online with discount in India'>"
+" <meta name='keywords' content='Sony NEX 3 ( with E 18-55mm Lens), buy, low, price, best, deals, India'>"
+" <meta http-equiv='Content-Type' content='text/html; charset=ISO-8859-1'>"

+" <title>Sony NEX 3 ( with E 18-55mm Lens) . Buy Best Sony NEX 3 ( with E 18-55mm Lens) at Lowest Price Online</title>"
    +" <meta name='Keywords' content='SRMShop, home, shopping, shop, 18, appliances, kitchen, cameras, mobiles, laptops, site, indian, gifts, apparel, buy, online, gifts'>"

+" <meta name='Description' content='online shopping india - buy home appliances, jewellery, home dicor, kitchen appliances, mobiles, digital cameras, laptops, apparel, furniture, gift items, bags, toys, footwear, from SRMShop.com at best prices.'>"
+" <meta name='google-site-verification' content='IolABglE0RhBY82vHxvaJwJymwcT1SWx9eHqs0Kewpo'>"

+"\n<!-- COMMON CSS INCLUDES -->\n"
+" <link href='http://stat.SRMShop.com/SRMShop/images/indexpage/images/favicon.ico?ver=v1.2.1' type='text/css' rel='shortcut icon' media='screen'>"
+" <link href='Home%20shop_files/common.css' type='text/css' rel='stylesheet' media='screen'>"
+" <link href='Home%20shop_files/jquery_002.css' type='text/css' rel='stylesheet' media='screen'>"
+" <link href='Home%20shop_files/category-search.css' type='text/css' rel='stylesheet' media='screen'>"
+" <link href='Home%20shop_files/skin.css' type='text/css' rel='stylesheet' media='screen'>"
+"\n<!-- Common CSS Library -->\n"
+"\n<!-- Jquery Library -->\n"
+" <script src='Home%20shop_files/beacon.js'></script><script src='Home%20shop_files/ga.js' type='text/javascript'></script><script src='Home%20shop_files/jquery-1.js' type='text/javascript' delayed='false' language='javascript'></script>"
+" <script src='Home%20shop_files/jquery-ui-1.js' type='text/javascript' delayed='false' language='javascript'></script>"
+" <script src='Home%20shop_files/jquery.js' type='text/javascript' delayed='false' language='javascript'></script>"
+"\n<!-- Product Details Page -->\n"
  +"\n<!-- Product Page css -->\n"
  +" <link href='Home%20shop_files/product_description.css' type='text/css' rel='stylesheet' media='screen'>"
+" <link href='Home%20shop_files/image_rotator.css' type='text/css' rel='stylesheet' media='screen'>"
+" <link href='Home%20shop_files/jquery.css' type='text/css' rel='stylesheet' media='screen'>"
+" <script type='text/javascript'>"
+"\nfunction displaymessage()"
+"\n{ alert(' Conform ');} </script>"

+" <script type='text/javascript'>"
			 +" function handleImgError(srcElement) "
			+"{     srcElement.src='http://stat.SRMShop.com/SRMShop/media/images/no-image-icon.jpg';       srcElement.onerror = ''; 	         return true;			}"
+" </script><meta property='fb:page_id' content='154457691255340'>"
  +" <meta property='fb:admins' content='744710176,100001731107204,538500576'>"
  +" <meta name='og_title' property='og:title' content='Sony NEX 3 ( with E 18-55mm Lens) . Buy Best Sony NEX 3 ( with E 18-55mm Lens) at Lowest Price Online'>"
  +" <meta name='og_site_name' property='og:site_name' content='SRMShop.com'>"
  +" <meta name='og_url' property='og:url' content='http://www.SRMShop.com/sony-nex-3-e-18-55mm-lens/camera-camcorders/digital-cameras/product:214869/cid:3183/'>"
  +" <link rel='canonical' href='http://www.SRMShop.com/sony-nex-3-e-18-55mm-lens/camera-camcorders/digital-cameras/product:214869/cid:3183/'>"


+ "\n<title>test</title><script src='Home%20shop_files/js' type='text/javascript'></script></head>"
                + " \n<body> ");
String[] paramValues = request.getParameterValues("Pcode");
codevalue = paramValues[0];
String[] paramValues1 = request.getParameterValues("Pprice");
 pricevalue = paramValues1[0];
         out.println("\n" + codevalue +"\n"+ pricevalue
                +" \n <div id='_atssh' style='visibility: hidden; height: 1px; width: 1px; position: absolute; z-index: 100000;'><iframe src='Home%20shop_files/sh33.htm' style='border: 0pt none ; height: 1px; width: 1px; position: absolute; z-index: 100000; left: 0pt; top: 0pt;' id='_atssh870'></iframe></div>"

      +" <script type='text/javascript' language='javascript'>"
     +" var heightScroll = 0; </script> \n <!-- Header starts --> "
                +" <div class='hdr_top_row2' >"
+" <div id='header_area'  >"
        +"<div id='logo_SRMShop' class='hdr_top_row2'>"
            +" <a href='http://www.SRMShop.com/'><img src='Home%20shop_files/logoSRMShop_x78.gif' alt='Online Shopping India - Shop Online For Jewellery, Home Appliances, Cameras, Mobiles from SRMShop' width='200' border='0' height='85'></a>"
        +" </div>    </div> </div> \n  <!-- Header ends --> \n <!-- Top nav starts --> \n   <div id='nav'>"
      +" <ul id='topnav' class='clearfix'>"
        +" <li class='nav1'>"
          +" <a href='#' class='navLink1'>All Categories</a>"
          +" <div style='opacity: 0;' class='sub'>"
            +" <ul id='sideNav'>"
	            +" <li class='sideArrow'>"
	            	+" <a href='http://books.SRMShop.com/books/category:3001/'>Books</a>"
			            +" <ul style='opacity: 0;' class='sideMenu'>"
		              		+" <li><a href='http://www.SRMShop.com/architecture-26-intertiors/category:3006/'>Architecture &amp; Interiors</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/art-26-design/category:3007/'>Art &amp; Design</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/biography-26-autobiography/category:3008/'>Biography &amp; Autobiography</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/business-26-management/category:3009/'>Business &amp; Management</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/children/category:3010/'>Children</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/fiction/category:3019/'>Fiction</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/food-26-drink/category:3022/'>Food &amp; Drink</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/health-26-fitness/category:3023/'>Health &amp; Fitness</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/history/category:3025/'>History</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/humor/category:3034/'>Humor</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/literature-26-language/category:3045/'>Literature &amp; Language</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/mind-2c-body-26-spirit/category:3046/'>Mind, Body &amp; Spirit</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/nature-26-animal-world/category:3047/'>Nature &amp; Animal World</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/non-fiction/category:3048/'>Non Fiction</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/reference/category:3051/'>Reference</a></li>"
		              	  +" <li><a href='http://www.SRMShop.com/religion-26-philosophy/category:3052/'>Religion &amp; Philosophy</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/science-26-maths/category:3053/'>Science &amp; Maths</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/self-improvement/category:3054/'>Self Improvement</a></li>"
		              	  +" <li><a href='http://www.SRMShop.com/sports-hobbies/category:3055/'>Sports and Hobbies</a></li>"
                                  +" <li><a href='http://www.SRMShop.com/travel/category:3056/'>Travel</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/dictionary/category:3005/'>Dictionary</a></li>"
		              	  +" <li><a href='http://www.SRMShop.com/computers-26-internet/category:3902/'>Computers &amp; Internet</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/academic/category:3903/'>Academic</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/medicine/category:3904/'>Medicine</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/astrology-26-occult/category:3906/'>Astrology &amp; Occult</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/gardening/category:3907/'>Gardening</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/sex-26-erotica/category:3908/'>Sex &amp; Erotica</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/professional-26-technical/category:3909/'>Professional &amp; Technical</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/parenting/category:3910/'>Parenting</a></li>"
		                  +" <li><a href='http://www.SRMShop.com/regional/category:3911/'>Regional</a></li>"
		              	+" </ul>"
	            +" </li>     <li class='sideArrow'>     	<a href='http://camera.SRMShop.com/camera-26-camcorders/category:3159/'>Cameras &amp; Camcorders</a>              	<ul style='opacity: 0;' class='sideMenu'>"
              		+" <li><a href='http://www.SRMShop.com/digital-cameras/category:3178/'>Digital Cameras</a></li>"
                  +" <li><a href='http://www.SRMShop.com/camcorders/category:3164/'>Camcorders</a></li>"
                 +" <li><a href='http://www.SRMShop.com/binoculars-26-telescopes/category:3161/'>Binoculars &amp; Telescopes</a></li>"
                  +" <li><a href='http://www.SRMShop.com/camera-26-camcorder-accessories/category:3170/'>Accessories</a></li>"
                  +" <li><a href='http://www.SRMShop.com/photo-frames/category:3561/'>Photo Frames</a></li>"
                  +" <li><a href='http://www.SRMShop.com/memory-26-storage-media/category:3192/'>Memory &amp; Storage</a></li>"
              	+" </ul>            	</li>              <li class='sideArrow'>	             	<a href='http://mobiles.SRMShop.com/mobiles-26-accessories/category:3024/'>Mobiles and Accessories</a> "
	             	+" <ul style='opacity: 0;' class='sideMenu'>"
	             		+" <li><a href='http://www.SRMShop.com/gsm-handsets/category:3027/'>Handsets</a></li>"
	                	+" <li><a href='http://www.SRMShop.com/accessories/category:3032/'>Accessories</a></li>"
	             	+"</ul>       	</li>"
              +" <li class='sideArrow'>"
              	+" <a href='http://apparel.SRMShop.com/apparel-accessories/category:3396/'>Apparel &amp; Accessories</a>"
              	+" <ul style='opacity: 0;' class='sideMenu'>"
              		+" <li><a href='http://www.SRMShop.com/women-27s-apparel/category:3431/'>Women's Apparel</a></li>"
                  +" <li><a href='http://www.SRMShop.com/women-27s-accessories/category:3450/'>Women's Accessories</a></li>"
                  +" <li><a href='http://www.SRMShop.com/men-27s-apparel/category:3404/'>Men's Apparel</a></li>"
                  +" <li><a href='http://www.SRMShop.com/men-27s-accessories/category:3419/'>Men's Accessories</a></li>"
                  +" <li><a href='http://www.SRMShop.com/bags-luggage/category:3397/'>Bags &amp; Luggage</a></li>"
                  +" <li><a href='http://www.SRMShop.com/footwear/category:3454/'>Footwear</a></li>"
              	+" </ul>      	</li>            <li class='sideArrow'>"
              	+" <a href='http://jewellery.SRMShop.com/jewellery-watches/category:3376/'>Jewellery &amp; Watches</a>"
                +" <ul style='opacity: 0;' class='sideMenu'>"
              		+" <li><a href='http://mobiles.SRMShop.com/bangles-26-bracelets/category:3379/'>Bangles &amp; Bracelets</a></li>"
                  +" <li><a href='http://apparel.SRMShop.com/ankle-bracelets/category:3378/'>Anklets</a></li>"
                  +" <li><a href='http://jewellery.SRMShop.com/earrings/category:3383/'>Earrings</a></li>"
                  +" <li><a href='http://www.SRMShop.com/fashion-jewellery/category:3390/'>Fashion Jewellery</a></li>"
                  +" <li><a href='http://home.SRMShop.com/men-27s-ring/category:3389/'>Men's ring</a></li>"
                  +" <li><a href='http://www.SRMShop.com/necklaces/category:3384/'>Necklaces</a></li>"
                  +" <li><a href='http://www.SRMShop.com/nosepins/category:3386/'>Nosepins</a></li>"
                  +" <li><a href='http://computer.SRMShop.com/pendants/category:3385/'>Pendants</a></li>"
                  +" <li><a href='http://kids.SRMShop.com/rings/category:3387/'>Rings</a></li>"
                  +" <li><a href='http://www.SRMShop.com/sets/category:3388/'>Sets</a></li>"
                  +" <li><a href='http://household.SRMShop.com/watches/category:3391/'>Watches</a></li>"
                  +" <li><a href='http://www.SRMShop.com/coins-gift-vouchers/category:3395/'>Coins</a></li>        	</ul>      </li>"
              +" <li class='sideArrow'>"
              	+" <a href='http://electronics.SRMShop.com/electronics/category:3203/'>Electronics</a>"
                +" <ul style='opacity: 0;' class='sideMenu'>"
              	  +" <li><a href='http://www.SRMShop.com/audio-26-video-players/category:3210/'>Audio &amp; Video Players</a></li>"
                  +" <li><a href='http://www.SRMShop.com/telephones/category:3232/'>Telephones</a></li>"
                  +" <li><a href='http://www.SRMShop.com/car-electronics/category:3204/'>Car Electronics</a></li>"
                  +" <li><a href='http://www.SRMShop.com/tv-27s-26-accessories/category:3236/'>TV &amp; Accessories</a></li>"
                  +" <li><a href='http://www.SRMShop.com/gaming/category:3243/'>Gaming Consoles</a></li>"
              	+"</ul>       	</li>         <li class='sideArrow'>"
                	+" <a href='http://home.SRMShop.com/home-kitchen/category:3503/'>Home &amp; Kitchen</a>"
                  +" <ul style='opacity: 0;' class='sideMenu'>"
                		+" <li><a href='http://www.SRMShop.com/bar-accessories/category:3504/'>Bar Accessories</a></li>"
                    +" <li><a href='http://www.SRMShop.com/bathroom-set/category:3745/'>Bathroom Set</a></li>"
                    +" <li><a href='http://www.SRMShop.com/cookware/category:3511/'>Cookware</a></li>"
                    +" <li><a href='http://www.SRMShop.com/dinner-sets-serveware/category:3522/'>Dinner Sets &amp; Serveware</a></li>"
                    +" <li><a href='http://www.SRMShop.com/furnishings/category:3533/'>Furnishings</a></li>"
                    +" <li><a href='http://www.SRMShop.com/furniture/category:3541/'>Furniture</a></li>"
                    +" <li><a href='http://www.SRMShop.com/hardware-2c-tools-fixtures/category:3547/'>Hardware, Tools, &amp; Fixtures</a></li>"
                    +" <li><a href='http://www.SRMShop.com/home-decor/category:3553/'>Home Décor</a></li>"
                    +" <li><a href='http://www.SRMShop.com/storage/category:3582/'>Storage</a></li>"
                    +" <li><a href='http://www.SRMShop.com/home-improvement/category:3567/'>Home Improvement</a></li>"
                    +" <li><a href='http://www.SRMShop.com/religion-spirituality/category:3570/'>Religion &amp; Spirituality</a></li>"
                    +" <li><a href='http://www.SRMShop.com/safety-security/category:3574/'>Safety &amp; Security</a></li>"
                	+" </ul>          </li>          <li class='sideArrow'> "
                	+" <a href='http://toys.SRMShop.com/toys-games/category:3335/'>Toys &amp; Games</a>"
                  +" <ul style='opacity: 0;' class='sideMenu'>"
                		+" <li><a href='http://www.SRMShop.com/action-toys-26-figures/category:3336/'>Action toys &amp; figures</a></li>"
                    +" <li><a href='http://www.SRMShop.com/baby-toys/category:3342/'>Baby Toys</a></li>"
                    +" <li><a href='http://www.SRMShop.com/dolls/category:3349/'>Dolls</a></li>"
                    +" <li><a href='http://www.SRMShop.com/educational-toys/category:3350/'>Educational Toys</a></li>"
                     +" <li><a href='http://www.SRMShop.com/electronic-toys/category:3337/'>Electronic Toys</a></li>"
                    +" <li><a href='http://www.SRMShop.com/indoor-games-26-puzzles/category:3343/'>Indoor Games &amp; Puzzles</a></li>"
                    +" <li><a href='http://www.SRMShop.com/inflatable-toys/category:3351/'>Inflatable Toys</a></li>"
                    +" <li><a href='http://www.SRMShop.com/outdoor-games/category:3361/'>Outdoor Games</a></li>"
                    +" <li><a href='http://www.SRMShop.com/soft-toys/category:3352/'>Soft Toys</a></li>"
                    +" <li><a href='http://www.SRMShop.com/video-games/category:3353/'>Video Games</a></li>"
                	+" </ul>            </li>            <li class='sideArrow'> "
                	+" <a href='http://gifts.SRMShop.com/gifts-flowers/category:3011/'>Gifts &amp; Flowers</a>"
                  +" <ul style='opacity: 0;' class='sideMenu'>"
                		+" <li><a href='http://www.SRMShop.com/cakes-cookies/category:3015/'>Cakes &amp; Cookies</a></li>"
                    +" <li><a href='http://www.SRMShop.com/chocolates/category:3016/'>Chocolates</a></li>"
                    +" <li><a href='http://www.SRMShop.com/flowers/category:3013/'>Flowers</a></li>"
                    +" <li><a href='http://www.SRMShop.com/gift-shop/category:3021/'>Gift Shop</a></li>"
                    +" <li><a href='http://www.SRMShop.com/sweets-26-dry-fruits/category:3018/'>Sweets &amp; Dry Fruits</a></li>"
                	+" </ul> "
                        +"</li>     <li class='sideArrow'> "
                	+" <a href='http://computer.SRMShop.com/computer-peripherals/category:3254/'>Computer &amp; Peripherals</a>"
                	+" <ul style='opacity: 0;' class='sideMenu'>"
                	+" <li><a href='http://www.SRMShop.com/computer-peripherals/category:3255/'>Computer Peripherals</a></li>"
                    +" <li><a href='http://www.SRMShop.com/laptop-components-26-accessories/category:3287/'>Laptop Components &amp; Accessories</a></li>"
                    +" <li><a href='http://www.SRMShop.com/software-cd-roms/category:3323/'>Software CD-ROMs</a></li>"
                    +" <li><a href='http://www.SRMShop.com/office-products/category:3303/'>Office Products</a></li>"
                    +" <li><a href='http://www.SRMShop.com/printers-2c-fax-26-scanners/category:3315/'>Printers, Fax &amp; Scanners</a></li>"
                    +" <li><a href='http://www.SRMShop.com/laptops/category:3291/'>Laptops</a></li>"
                    +" <li><a href='http://www.SRMShop.com/networking-equipment/category:3299/'>Networking Equipment</a></li>"
                    +" <li><a href='http://www.SRMShop.com/printer-supplies/category:3311/'>Printer Supplies</a></li>"
                    +" <li><a href='http://www.SRMShop.com/others/category:3334/'>Others</a></li>"
                	+" </ul>	</li>                <li class='sideArrow'>"
                	+" <a href='http://kids.SRMShop.com/kids-26-baby/category:3627/'>Kids &amp; Baby</a>"
                	+" <ul style='opacity: 0;' class='sideMenu'>"
                	+" <li><a href='http://www.SRMShop.com/baby/category:3462/'>Baby</a></li>"
                    +" <li><a href='http://www.SRMShop.com/kids/category:3458/'>Kids</a></li>"
                	+" </ul>          </li>          <li class='sideArrow'>"
                	+" <a href='http://health.SRMShop.com/health-beauty/category:3471/'>Health &amp; Beauty</a>"
                	+" <ul style='opacity: 0;' class='sideMenu'>"
                	+" <li><a href='http://www.SRMShop.com/perfumes-deos/category:3475/'>Perfumes and Deos</a></li> "
                           +"</ul>              </li>"
                +" <li class='sideArrow'>"
                	+" <a href='http://movies.SRMShop.com/movies/category:3003/'>Movies</a>"
                	+" <ul style='opacity: 0;' class='sideMenu'>"
                	+" <li><a href='http://www.SRMShop.com/english/category:3063/'>English</a></li>"
                    +" <li><a href='http://www.SRMShop.com/hindi/category:3064/'>Hindi</a></li>"
                    +" <li><a href='http://www.SRMShop.com/marathi/category:3853/'>Marathi</a></li>"
                	+" </ul>          </li>"
            +"  </ul>        </div>       </li>"
        +" <li class='nav2'>"
          +" <a href='http://books.SRMShop.com/books/category:3001/' class='navLink2 nav'>Books</a>      </li> "
        +" <li class='nav3'>"
          +" <a href='http://mobiles.SRMShop.com/mobiles-26-accessories/category:3024/' class='navLink3 nav'>Mobiles</a>      </li> "
        +" <li class='nav4'>"
          +" <a href='http://camera.SRMShop.com/camera-26-camcorders/category:3159/' class='navLink4 nav'>Cameras</a>    </li>"
        +" <li class='nav5'>"
          +" <a href='http://electronics.SRMShop.com/electronics/category:3203/' class='navLink5 nav'>Electronics</a>    </li> "
        +" <li class='nav6'>"
        + "   <a href='http://apparel.SRMShop.com/apparel-accessories/category:3396/' class='navLink6 nav'>Apparel &amp; more</a>    </li> "
        +" <li class='nav7'> "
          +" <a href='http://jewellery.SRMShop.com/jewellery-watches/category:3376/' class='navLink7 nav'>Jewellery &amp; Watches</a>  </li> "
        +" <li class='nav8'> "
          +" <a href='http://home.SRMShop.com/home-kitchen/category:3503/' class='navLink8 nav'>Home &amp; Kitchen</a>  </li> "
        + " <li class='nav9'> "
          +" <a href='http://toys.SRMShop.com/toys-games/category:3335/' class='navLink9 nav'>Toys</a>   </li> "
        + " <li class='nav10'> "
          +" <a href='http://gifts.SRMShop.com/gifts-flowers/category:3011/' class='navLink10 nav'>Gifts</a>    </li>  </ul>   "
                +" </div>  <br > <br > <br > <br > \n"
                +" <!--INPUT OF BANK--> \n "
                + " <div id='header_area'  > "
+" \n <FORM action='https://localhost:8181/WebApplication4/page3 ' method='post'> "
+" \n <p style='font-family:Roman;color:RED;font-size:18px; '>Select the type of card and it's bank </p><br ><br>"
+" <ul >	<div  class='ftr_sections' > <li> <h4 style='font-family:arial;color:blue;font-size:20px; '>Credit Card</h4> "
		+" <ol> "
		+" <li><INPUT TYPE='RADIO' NAME ='bank' VALUE='cicici'/> ICICI"
		+" <li><INPUT TYPE='RADIO' NAME ='bank' VALUE='cidbi'/> IDBI"
		+" </ol></div>"
	+" <li>  <div  class='ftr_sections' ><h4 style='font-family:arial;color:blue;font-size:20px; '>Debit Card</h4>"
		+" <ol>"
		+" <li><INPUT TYPE='RADIO' NAME ='bank' VALUE='dsbi'/> SBI"
		+" <li><INPUT TYPE='RADIO' NAME ='bank' VALUE='didbi'/> IDBI"
		+" <li><INPUT TYPE='RADIO' NAME ='bank' VALUE='daxis'/> Axis"
		+" <li><INPUT TYPE='RADIO' NAME ='bank' VALUE='dindia'/> Bank of india"
		+" </ol></div>"
                 +" <li> <div  class='ftr_sections' > <h4 style='font-family:arial;color:blue;font-size:20px; '>Net Banking</h4>"
		+" <ol>"
		+" <li><INPUT TYPE='RADIO' NAME ='bank' VALUE='nsbi'/> SBI"
		+" <li><INPUT TYPE='RADIO' NAME ='bank' VALUE='nidbi'/> IDBI"
		+" <li><INPUT TYPE='RADIO' NAME ='bank' VALUE='naxis'/> Axis"
		+" <li><INPUT TYPE='RADIO' NAME ='bank' VALUE='nindia'/> Bank of india"
		+" </ol></div>"
                
+" </ul><div class='ftr_row1' ><br > "
+"<br><br ><br><br ><br > \n "
                          +" <INPUT  type='image' src='Home shop_files/btn_next.png'   width='80'  height='28'  />"
+" </form><div>"

+" </div> <br ><br ><br>"
+" <div class='ftr_row1'   id='header_area'>"
        +" <div class='ftr_sections'> "
            +" <h2 class='ftr_section_hdr'>Shopping with Us</h2>"
			+" <a href='http://www.SRMShop.com/track-your-order.html' title='Track an Order' target='_blank'>Track an Order</a>"
			+" <a href='javascript:void(0);' onclick='window.open('/shop/faces/jsp/popup/call-customer-care.html','name','height=515, width=410,toolbar=no,directories=no,status=no, menubar=no,scrollbars=yes,resizable=no'); return false;' title='Customer Care Team'>Customer Care Team</a>"
			+" <a href='http://help.SRMShop.com/forums/302968-payment-related' target='_blank' title='SRMShop : Payment Options'>Payment Options</a>"
			+" <a href='http://help.SRMShop.com/' target='_blank' title='SRMShop : Help Desk'>Help Desk</a>"

			+" <a href='http://www.SRMShop.com/return-policy.html' target='_blank' title='SRMShop : Return Policy'>Return Policy</a>"
			+" <a href='http://www.SRMShop.com/shipping-policy.html' target='_blank' title='SRMShop : Shipping Policy'>Shipping Policy</a>"
			+" <a href='http://www.SRMShop.com/why-SRMShop.html' target='_blank' title='SRMShop : Why SRMShop'>Why SRMShop</a>"
        +" </div>      \n <div class='ftr_sections'> "
			+" <h2 class='ftr_section_hdr'>Help</h2> "
      			+" <a href='http://help.SRMShop.com/' title='SRMShop : FAQs and Help' target='_blank'>FAQs/Help</a>"
			+" <a href='http://www.SRMShop.com/shopping-demo.html'>Shopping Demo</a>"
			+" <a href='http://www.SRMShop.com/weekly-schedule.html' title=' SRMShop : TV Schedule' target='_blank'>TV Schedule</a>"
			+" <a href='http://www.SRMShop.com/partner-with-us.html' title=' SRMShop : Partner with Us' target='_blank'>Partner with Us</a>"
			+" <a href='http://www.SRMShop.com/shop/faces/sitemap.xml' title='Sitemap XML' target='_blank'>Sitemap <img alt='Site map' src='Home%20shop_files/icon_xml.gif' width='30' height='12'></a>"
			+" <a href='http://www.SRMShop.com/privacy-policy.html' title=' SRMShop : Privacy Policy' target='_blank'>Privacy Policy</a>"
			+" <a href='http://www.SRMShop.com/security-policy.html' title=' SRMShop : Security Policy' target='_blank'>Security Policy</a>"
        +"</div>      \n  <div class='ftr_sections'> "
            +" <h2 class='ftr_section_hdr'>About Us</h2> "
            +" <a href='http://www.SRMShop.com/about-us.html' title='About SRMShop' target='_blank'>About SRMShop</a>"
            +" <a href='http://www.SRMShop.com/awards.html' title='SRMShop : Awards' target='_blank'>Awards</a>"
            +" <a href='http://www.SRMShop.com/careers.html' title='SRMShop : Careers' target='_blank'>Careers</a>"
            +" <a href='http://www.SRMShop.com/feedback.html' title='SRMShop : Share your feedback' target='_blank'>Feedback</a>"
            +" <a href='http://www.SRMShop.com/investors.html' title='SRMShop : Investors' target='_blank'>Investors</a> "
            +" <a href='http://www.SRMShop.com/terms-conditions.html' title='SRMShop : Terms of Use' target='_blank'>Terms of Use</a>"
        +"</div>    </div>\n    <!-- ==== FTR ROW1 ENDS =====-->\n "

    +" <div class='ftr_row2'> \n"
        +" <div class='secure_icons'> \n"
+" <img src='Home%20shop_files/imgSecuredIcons.gif' usemap='#SecuredBy' alt='Secured by thawtes, Secured by MasterCard SecureCode, VERIFIED by VISA ,Secured By 4-D Secure' width='300' border='0' height='65'><br> "
		+" <map name='SecuredBy' id='SecuredBy'>"
			+ " <area shape='rect' coords='2,2,35,55' href='http://www.SRMShop.com/shop/faces/tiles/templates/media/misc/SRMShop/paymentoptions.jsp#a12_1' target='name' onclick='window.open('https://sealinfo.thawte.com/thawtesplash?form_file=fdf/thawtesplash.fdf&amp;dn=WWW.SRMShop.COM&amp;lang=en','name','height=650, width=520,toolbar=no,directories=no,status=no, menubar=no,scrollbars=yes,resizable=no'); return false;' alt='Secured by thawtes' title='Secured by thawtes'>"
			+" <area shape='rect' coords='56,2,125,75' href='http://www.SRMShop.com/shop/faces/tiles/templates/media/misc/SRMShop/paymentoptions.jsp#a12_1' target='name' onclick='window.open('/shop/faces/tiles/templates/media/misc/SRMShop/mastercardsecure.html','name','height=300, width=410,toolbar=no,directories=no,status=no, menubar=no,scrollbars=yes,resizable=no'); return false;' alt='Secured by MasterCard SecureCode' title='Secured by MasterCard SecureCode'>"
			+" <area shape='rect' coords='79,2,200,61' href='http://www.SRMShop.com/shop/faces/tiles/templates/media/misc/SRMShop/paymentoptions.jsp#a12_1' target='name' onclick='window.open('/shop/faces/tiles/templates/media/misc/SRMShop/visasecure.html','name','height=310, width=400,toolbar=no,directories=no,status=no, menubar=no,scrollbars=yes,resizable=no'); return false;' alt='VERIFIED by VISA' title='VERIFIED by VISA'>"
		                 +" <area shape='rect' coords='80,2,300,61' href='http://www.SRMShop.com/shop/faces/tiles/templates/media/misc/SRMShop/paymentoptions.jsp#a12_1' target='name' onclick='window.open('/shop/faces/tiles/templates/media/misc/SRMShop/visasecure.html','name','height=310, width=400,toolbar=no,directories=no,status=no, menubar=no,scrollbars=yes,resizable=no'); return false;' alt='VERIFIED by 4-D Secure' title='VERIFIED by 4-D secure'>"
                      +" </map> \n"
        +" </div>    </div><div class='ftr_endtxt'>© 2011 SRMShop All rights reserved.</div></div><script type='text/JavaScript'> "
                +" \n <!-- COMMON JS INCLUDES --> \n"
        +" <script src='Home%20shop_files/img_change.js' type='text/javascript' delayed='false' language='javascript'></script> "
+" \n<script src='Home%20shop_files/login-toggle.js' type='text/javascript' delayed='false' language='javascript'></script>"
+" \n<script src='Home%20shop_files/common.js' type='text/javascript' delayed='false' language='javascript'></script> "
+" \n<script type='text/JavaScript'>"
+" \npageType = 'review';"
		+" \n </script>"
  +" \n <!-- Mega Menu -->\n "
+" <script src='Home%20shop_files/jquery-hoverIntent.js' type='text/javascript' delayed='false' language='javascript'></script> \n"
+" </form></body></html>");


    } 
    @Override
public void doPost(HttpServletRequest request,
HttpServletResponse response)
throws ServletException, IOException {
doGet(request, response);
}

}
